import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../profiles/domain/grade_level.dart';
import '../domain/lesson.dart';
import '../domain/subject.dart';
import 'lesson_parser.dart';
import 'question_factory.dart';

/// Loads curriculum content. Today it reads bundled JSON assets (offline-first);
/// the same interface can later fetch from Firestore/Storage and cache locally,
/// with zero changes to callers.
class CurriculumRepository {
  CurriculumRepository();

  final Map<String, Lesson> _lessons = {};
  final List<Unit> _units = [];
  bool _loaded = false;

  /// Asset files per grade. As more grades are authored, add them here.
  static const _assetByGrade = {
    GradeLevel.lkg: 'assets/data/curriculum_lkg.json',
    GradeLevel.ukg: 'assets/data/curriculum_ukg.json',
    GradeLevel.kg: 'assets/data/curriculum_kg.json',
    GradeLevel.grade1: 'assets/data/curriculum_grade1.json',
    GradeLevel.grade2: 'assets/data/curriculum_grade2.json',
    GradeLevel.grade3: 'assets/data/curriculum_grade3.json',
    GradeLevel.grade4: 'assets/data/curriculum_grade4.json',
    GradeLevel.grade5: 'assets/data/curriculum_grade5.json',
  };

  /// Levels every subject offers, in every grade.
  static const int _levelsPerUnit = 50;

  /// Session length follows attention span as well as game type. Preschool
  /// children get short, finishable wins; older children build towards longer
  /// missions. A level should end while the child still wants one more turn.
  static int _questionCountFor(GameType gameType, GradeLevel grade) {
    final standard = switch (grade) {
      GradeLevel.lkg => 5,
      GradeLevel.ukg => 7,
      GradeLevel.kg => 8,
      GradeLevel.grade1 => 10,
      GradeLevel.grade2 => 12,
      GradeLevel.grade3 => 12,
      GradeLevel.grade4 => 15,
      GradeLevel.grade5 => 15,
    };
    return switch (gameType) {
      GameType.memoryMatch => 1,
      GameType.tracing => standard.clamp(4, 8),
      GameType.sequence => standard.clamp(3, 6),
      GameType.flashcard => standard.clamp(5, 12),
      _ => standard,
    };
  }

  Future<void> ensureLoaded() async {
    if (_loaded) return;
    for (final entry in _assetByGrade.entries) {
      await _loadAsset(entry.value, entry.key);
    }
    // EVERY subject in EVERY grade becomes a full 50-level journey of freshly
    // generated, grade-appropriate, non-repeating questions.
    for (final grade in GradeLevel.values) {
      _buildJourneys(grade);
    }
    _loaded = true;
  }

  /// For each subject unit in [grade], builds [_levelsPerUnit] levels. The
  /// authored lessons act as *seeds* — they define the subject, the mix of
  /// mini-game types, and the artwork — while the questions themselves are
  /// generated by [QuestionFactory] so every level is fresh and correct.
  void _buildJourneys(GradeLevel grade) {
    final unitIndices = [
      for (var i = 0; i < _units.length; i++)
        if (_units[i].grade == grade) i,
    ];

    for (final unitIndex in unitIndices) {
      final unit = _units[unitIndex];
      final seeds = lessonsForUnit(unit);
      if (seeds.isEmpty) continue;

      // Rotate through the mini-game types this subject uses, for play variety.
      final gameTypes = seeds.map((s) => s.gameType).toSet().toList();

      // Fold in a "learn" flashcard track so foundational skills — the
      // alphabet (A–Z), numbers, and times tables — are taught, not just
      // quizzed. Math learns numbers/tables at every grade; English teaches
      // A–Z in the preschool bands.
      final wantsFlashcards = unit.subject == Subject.math ||
          (grade.isPreSchool &&
              (unit.subject == Subject.english ||
                  unit.subject == Subject.rhymes));
      if (wantsFlashcards && !gameTypes.contains(GameType.flashcard)) {
        gameTypes.insert(0, GameType.flashcard);
      }

      final ids = <String>[];

      for (var level = 1; level <= _levelsPerUnit; level++) {
        final gameType = gameTypes[(level - 1) % gameTypes.length];
        final seed = seeds[(level - 1) % seeds.length];
        final id = '${unit.id}_level_$level';
        _lessons[id] = Lesson(
          id: id,
          title: '${unit.title} · Level $level',
          subject: unit.subject,
          grade: grade,
          gameType: gameType,
          questions: QuestionFactory.forLevel(
            grade: grade,
            subject: unit.subject,
            gameType: gameType,
            level: level,
            count: _questionCountFor(gameType, grade),
          ),
          emoji: seed.emoji,
          instruction: seed.instruction,
          baseCoins: 10 + level,
          baseXp: 20 + level * 2,
        );
        ids.add(id);
      }

      _units[unitIndex] = Unit(
        id: unit.id,
        title: unit.title,
        subject: unit.subject,
        grade: grade,
        lessonIds: ids,
        emoji: unit.emoji,
      );
    }
  }

  Future<void> _loadAsset(String path, GradeLevel grade) async {
    try {
      final raw = await rootBundle.loadString(path);
      final json = jsonDecode(raw) as Map<String, dynamic>;

      for (final u in (json['units'] as List? ?? const [])) {
        final m = (u as Map).cast<String, dynamic>();
        _units.add(
          Unit(
            id: m['id'] as String,
            title: m['title'] as String,
            subject: Subject.fromId(m['subject'] as String),
            grade: GradeLevel.fromId(m['grade'] as String),
            emoji: m['emoji'] as String? ?? '📚',
            lessonIds: (m['lessonIds'] as List?)?.cast<String>() ?? const [],
          ),
        );
      }
      for (final l in (json['lessons'] as List? ?? const [])) {
        final lesson =
            LessonParser.lessonFromJson((l as Map).cast<String, dynamic>());
        _lessons[lesson.id] = lesson;
      }
    } catch (e) {
      // A missing/malformed grade file must not crash the app.
      if (kDebugMode) {
        debugPrint('Curriculum load failed for $path: $e');
      }
    }
  }

  List<Unit> unitsForGrade(GradeLevel grade) =>
      _units.where((u) => u.grade == grade).toList();

  List<Unit> unitsForGradeSubject(GradeLevel grade, Subject subject) =>
      _units.where((u) => u.grade == grade && u.subject == subject).toList();

  Lesson? lessonById(String id) => _lessons[id];

  List<Lesson> lessonsForUnit(Unit unit) =>
      unit.lessonIds.map((id) => _lessons[id]).whereType<Lesson>().toList();

  Set<Subject> subjectsForGrade(GradeLevel grade) =>
      unitsForGrade(grade).map((u) => u.subject).toSet();
}

final curriculumRepositoryProvider = Provider<CurriculumRepository>((ref) {
  return CurriculumRepository();
});

/// Loads (once) and exposes the curriculum so screens can `.when(...)` on it.
final curriculumLoadProvider =
    FutureProvider<CurriculumRepository>((ref) async {
  final repo = ref.watch(curriculumRepositoryProvider);
  await repo.ensureLoaded();
  return repo;
});
