"""Downloads the OpenMoji color PNGs for exactly the emoji used in the
curriculum (and a few app-wide ones), then generates a Dart lookup map.

OpenMoji (https://openmoji.org) is CC BY-SA 4.0 — consistent, colorful, flat
illustrations kids relate to far better than platform system emoji. We bundle
only the subset we use (~120 files, tiny) rather than the full 4000+ set.

Run:  python tool/fetch_openmoji.py
Outputs:
  assets/openmoji/<CODEPOINTS>.png            (downloaded images)
  lib/core/widgets/openmoji_map.g.dart        (emoji -> asset base name)
"""
import json
import os
import re
import glob
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "assets", "openmoji")
MAP_DART = os.path.join(ROOT, "lib", "core", "widgets", "openmoji_map.g.dart")
BASE_URL = "https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/72x72/"

# Extra emoji used in Dart (collectibles, shop, mascots) worth covering.
EXTRA = [
    "🐶", "🐱", "🐰", "🦊", "🐧", "🦄", "🐲", "⭐", "🌈", "🌸", "🎈",
    "🚀", "👑", "🏅", "💎", "🏆", "🥚", "🐼", "🦁", "🦉", "🤖",
    "🌅", "🌴", "🌊", "🍭", "🌙", "🎯", "🪙", "💎", "🎤", "🎉",
]


def collect_emoji():
    found = set(EXTRA)
    for path in glob.glob(os.path.join(ROOT, "assets", "data", "*.json")):
        with open(path, encoding="utf-8") as f:
            txt = f.read()
        for m in re.findall(r'"emoji"\s*:\s*"([^"]+)"', txt):
            found.add(m)
        for m in re.findall(r'"promptEmoji"\s*:\s*"([^"]+)"', txt):
            found.add(m)
    return sorted(found)


def candidates(emoji):
    """OpenMoji filename candidates for an emoji string, most-specific first."""
    cps = [f"{ord(c):04X}" for c in emoji]
    full = "-".join(cps)
    # Common variants: drop trailing FE0F variation selectors.
    no_fe0f = "-".join(cp for cp in cps if cp != "FE0F")
    out = []
    for name in (full, no_fe0f):
        if name and name not in out:
            out.append(name)
    return out


def download(name):
    url = BASE_URL + name + ".png"
    dest = os.path.join(OUT_DIR, name + ".png")
    if os.path.exists(dest):
        return True
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "kidverse"})
        with urllib.request.urlopen(req, timeout=20) as r:
            data = r.read()
        if len(data) < 200:
            return False
        with open(dest, "wb") as f:
            f.write(data)
        return True
    except Exception:
        return False


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    emojis = collect_emoji()
    mapping = {}
    ok, miss = 0, []
    for e in emojis:
        for name in candidates(e):
            if download(name):
                mapping[e] = name
                ok += 1
                break
        else:
            miss.append(e)
    # Emit the Dart map.
    lines = [
        "// GENERATED by tool/fetch_openmoji.py — do not edit by hand.",
        "// Maps an emoji string to its bundled OpenMoji asset base name",
        "// (assets/openmoji/<name>.png). OpenMoji art is CC BY-SA 4.0.",
        "const Map<String, String> kOpenMojiFiles = {",
    ]
    for e in sorted(mapping):
        esc = e.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  '{esc}': '{mapping[e]}',")
    lines.append("};")
    with open(MAP_DART, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"downloaded {ok}/{len(emojis)} emoji")
    if miss:
        print("missing (will fall back to code-drawn art):", " ".join(miss))


if __name__ == "__main__":
    main()
