/// Voice-ready preschool picture words keyed by category id.
///
/// Every category intentionally contains exactly 30 concrete, familiar words.
/// Emoji are lightweight visual cues; the spoken and written name is the
/// learning source of truth.
const Map<String, List<(String, String)>> preschoolPictureWords = {
  'body_parts': [
    ('Head', '🙂'),
    ('Hair', '💇'),
    ('Forehead', '🙂'),
    ('Face', '😊'),
    ('Eyes', '👀'),
    ('Eyebrows', '🤨'),
    ('Eyelashes', '👁️'),
    ('Ears', '👂'),
    ('Nose', '👃'),
    ('Cheeks', '😊'),
    ('Mouth', '👄'),
    ('Lips', '👄'),
    ('Teeth', '🦷'),
    ('Tongue', '👅'),
    ('Chin', '🙂'),
    ('Neck', '🧣'),
    ('Shoulders', '🤷'),
    ('Chest', '🫁'),
    ('Back', '🔙'),
    ('Stomach', '🫃'),
    ('Waist', '🧍'),
    ('Arms', '💪'),
    ('Elbows', '💪'),
    ('Wrists', '🤚'),
    ('Hands', '🤲'),
    ('Fingers', '🖐️'),
    ('Thumbs', '👍'),
    ('Legs', '🦵'),
    ('Knees', '🦵'),
    ('Feet', '🦶'),
  ],
  'fruits': [
    ('Apple', '🍎'),
    ('Banana', '🍌'),
    ('Mango', '🥭'),
    ('Orange', '🍊'),
    ('Grapes', '🍇'),
    ('Watermelon', '🍉'),
    ('Strawberry', '🍓'),
    ('Pineapple', '🍍'),
    ('Pear', '🍐'),
    ('Peach', '🍑'),
    ('Cherry', '🍒'),
    ('Coconut', '🥥'),
    ('Lemon', '🍋'),
    ('Kiwi', '🥝'),
    ('Papaya', '🧡'),
    ('Guava', '🍈'),
    ('Pomegranate', '🔴'),
    ('Blueberry', '🫐'),
    ('Raspberry', '🫐'),
    ('Blackberry', '🫐'),
    ('Plum', '🟣'),
    ('Apricot', '🟠'),
    ('Fig', '🟣'),
    ('Date', '🟤'),
    ('Lychee', '🔴'),
    ('Dragon fruit', '🐉'),
    ('Custard apple', '🍏'),
    ('Muskmelon', '🍈'),
    ('Star fruit', '⭐'),
    ('Jackfruit', '💚'),
  ],
  'vegetables': [
    ('Carrot', '🥕'),
    ('Tomato', '🍅'),
    ('Potato', '🥔'),
    ('Onion', '🧅'),
    ('Broccoli', '🥦'),
    ('Corn', '🌽'),
    ('Peas', '🫛'),
    ('Cucumber', '🥒'),
    ('Brinjal', '🍆'),
    ('Capsicum', '🫑'),
    ('Mushroom', '🍄'),
    ('Spinach', '🥬'),
    ('Pumpkin', '🎃'),
    ('Garlic', '🧄'),
    ('Sweet potato', '🍠'),
    ('Cabbage', '🥬'),
    ('Cauliflower', '🥦'),
    ('Radish', '🤍'),
    ('Beetroot', '🟣'),
    ('Okra', '💚'),
    ('Beans', '🫘'),
    ('Ginger', '🫚'),
    ('Turnip', '🤍'),
    ('Bottle gourd', '🥒'),
    ('Bitter gourd', '🥒'),
    ('Ladyfinger', '💚'),
    ('Lettuce', '🥬'),
    ('Celery', '🌿'),
    ('Green chilli', '🌶️'),
    ('Coriander', '🌿'),
  ],
  'animals': [
    ('Cat', '🐱'),
    ('Dog', '🐶'),
    ('Cow', '🐄'),
    ('Goat', '🐐'),
    ('Horse', '🐴'),
    ('Rabbit', '🐰'),
    ('Lion', '🦁'),
    ('Tiger', '🐯'),
    ('Elephant', '🐘'),
    ('Monkey', '🐒'),
    ('Bear', '🐻'),
    ('Fox', '🦊'),
    ('Deer', '🦌'),
    ('Camel', '🐪'),
    ('Giraffe', '🦒'),
    ('Zebra', '🦓'),
    ('Panda', '🐼'),
    ('Pig', '🐷'),
    ('Sheep', '🐑'),
    ('Kangaroo', '🦘'),
    ('Rhinoceros', '🦏'),
    ('Hippopotamus', '🦛'),
    ('Wolf', '🐺'),
    ('Squirrel', '🐿️'),
    ('Mouse', '🐭'),
    ('Donkey', '🫏'),
    ('Buffalo', '🐃'),
    ('Leopard', '🐆'),
    ('Gorilla', '🦍'),
    ('Koala', '🐨'),
  ],
  'birds': [
    ('Parrot', '🦜'),
    ('Peacock', '🦚'),
    ('Owl', '🦉'),
    ('Duck', '🦆'),
    ('Hen', '🐔'),
    ('Chick', '🐥'),
    ('Eagle', '🦅'),
    ('Swan', '🦢'),
    ('Flamingo', '🦩'),
    ('Penguin', '🐧'),
    ('Dove', '🕊️'),
    ('Crow', '🐦‍⬛'),
    ('Sparrow', '🐦'),
    ('Pigeon', '🕊️'),
    ('Kingfisher', '🐦'),
    ('Woodpecker', '🐦'),
    ('Mynah', '🐦'),
    ('Cuckoo', '🐦'),
    ('Nightingale', '🐦'),
    ('Robin', '🐦'),
    ('Turkey', '🦃'),
    ('Rooster', '🐓'),
    ('Goose', '🪿'),
    ('Seagull', '🐦'),
    ('Pelican', '🐦'),
    ('Stork', '🐦'),
    ('Crane', '🐦'),
    ('Ostrich', '🐦'),
    ('Kiwi bird', '🐦'),
    ('Hummingbird', '🐦'),
  ],
  'colors': [
    ('Red', '🔴'),
    ('Blue', '🔵'),
    ('Green', '🟢'),
    ('Yellow', '🟡'),
    ('Orange', '🟠'),
    ('Purple', '🟣'),
    ('Pink', '🩷'),
    ('Brown', '🟤'),
    ('Black', '⚫'),
    ('White', '⚪'),
    ('Grey', '🩶'),
    ('Violet', '💜'),
    ('Indigo', '🔵'),
    ('Gold', '🟨'),
    ('Silver', '⬜'),
    ('Beige', '🟨'),
    ('Maroon', '🔴'),
    ('Navy blue', '🔵'),
    ('Sky blue', '🩵'),
    ('Light green', '💚'),
    ('Dark green', '🟢'),
    ('Peach', '🍑'),
    ('Coral', '🪸'),
    ('Turquoise', '🩵'),
    ('Lavender', '🪻'),
    ('Magenta', '🩷'),
    ('Cream', '🤍'),
    ('Tan', '🟤'),
    ('Mint', '🍃'),
    ('Rainbow', '🌈'),
  ],
  'shapes': [
    ('Circle', '🔵'),
    ('Square', '🟥'),
    ('Triangle', '🔺'),
    ('Rectangle', '▭'),
    ('Oval', '🥚'),
    ('Star', '⭐'),
    ('Heart', '❤️'),
    ('Diamond', '🔷'),
    ('Semicircle', '◒'),
    ('Crescent', '🌙'),
    ('Pentagon', '⬟'),
    ('Hexagon', '⬡'),
    ('Octagon', '🛑'),
    ('Cross', '✚'),
    ('Arrow', '➡️'),
    ('Cube', '🧊'),
    ('Sphere', '🌐'),
    ('Cone', '🍦'),
    ('Cylinder', '🥫'),
    ('Pyramid', '🔺'),
    ('Ring', '⭕'),
    ('Spiral', '🌀'),
    ('Line', '➖'),
    ('Dot', '🔵'),
    ('Kite shape', '🔶'),
    ('Cloud', '☁️'),
    ('Flower shape', '🌸'),
    ('Drop', '💧'),
    ('Plus', '➕'),
    ('Zigzag', '〽️'),
  ],
  'family': [
    ('Mother', '👩'),
    ('Father', '👨'),
    ('Sister', '👧'),
    ('Brother', '👦'),
    ('Grandmother', '👵'),
    ('Grandfather', '👴'),
    ('Baby', '👶'),
    ('Aunt', '👩‍🦱'),
    ('Uncle', '👨‍🦱'),
    ('Family', '👨‍👩‍👧‍👦'),
    ('Parents', '👫'),
    ('Children', '🧒'),
    ('Daughter', '👧'),
    ('Son', '👦'),
    ('Cousin', '🧒'),
    ('Niece', '👧'),
    ('Nephew', '👦'),
    ('Great-grandmother', '👵'),
    ('Great-grandfather', '👴'),
    ('Twins', '👯'),
    ('Older sister', '👧'),
    ('Younger sister', '👧'),
    ('Older brother', '👦'),
    ('Younger brother', '👦'),
    ('Maternal grandmother', '👵'),
    ('Paternal grandmother', '👵'),
    ('Maternal grandfather', '👴'),
    ('Paternal grandfather', '👴'),
    ('Guardian', '🧑'),
    ('Pet', '🐶'),
  ],
  'transport': [
    ('Car', '🚗'),
    ('Bus', '🚌'),
    ('Train', '🚂'),
    ('Bicycle', '🚲'),
    ('Scooter', '🛵'),
    ('Truck', '🚚'),
    ('Ambulance', '🚑'),
    ('Fire engine', '🚒'),
    ('Aeroplane', '✈️'),
    ('Helicopter', '🚁'),
    ('Boat', '⛵'),
    ('Ship', '🚢'),
    ('Taxi', '🚕'),
    ('Auto rickshaw', '🛺'),
    ('Motorcycle', '🏍️'),
    ('Tractor', '🚜'),
    ('School bus', '🚌'),
    ('Metro train', '🚇'),
    ('Tram', '🚊'),
    ('Monorail', '🚝'),
    ('Rocket', '🚀'),
    ('Hot-air balloon', '🎈'),
    ('Canoe', '🛶'),
    ('Speedboat', '🚤'),
    ('Sailboat', '⛵'),
    ('Ferry', '⛴️'),
    ('Police car', '🚓'),
    ('Delivery van', '🚐'),
    ('Cable car', '🚠'),
    ('Wheelchair', '🦽'),
  ],
  'everyday': [
    ('Book', '📖'),
    ('Pencil', '✏️'),
    ('Crayon', '🖍️'),
    ('Bag', '🎒'),
    ('Chair', '🪑'),
    ('Table', '🪵'),
    ('Cup', '🥤'),
    ('Plate', '🍽️'),
    ('Spoon', '🥄'),
    ('Toothbrush', '🪥'),
    ('Soap', '🧼'),
    ('Towel', '🧻'),
    ('Clock', '🕐'),
    ('Bed', '🛏️'),
    ('Door', '🚪'),
    ('Key', '🔑'),
    ('Umbrella', '☂️'),
    ('Bottle', '🍼'),
    ('Comb', '🪮'),
    ('Mirror', '🪞'),
    ('Telephone', '☎️'),
    ('Lamp', '💡'),
    ('Fan', '🪭'),
    ('Bucket', '🪣'),
    ('Basket', '🧺'),
    ('Scissors', '✂️'),
    ('Box', '📦'),
    ('Ball', '⚽'),
    ('Watch', '⌚'),
    ('Glasses', '👓'),
  ],
  'farm_animals': [
    ('Cow', '🐄'),
    ('Calf', '🐮'),
    ('Buffalo', '🐃'),
    ('Bull', '🐂'),
    ('Goat', '🐐'),
    ('Kid goat', '🐐'),
    ('Sheep', '🐑'),
    ('Lamb', '🐑'),
    ('Horse', '🐴'),
    ('Pony', '🐴'),
    ('Donkey', '🫏'),
    ('Pig', '🐷'),
    ('Piglet', '🐖'),
    ('Rabbit', '🐰'),
    ('Hen', '🐔'),
    ('Rooster', '🐓'),
    ('Chick', '🐥'),
    ('Duck', '🦆'),
    ('Duckling', '🐤'),
    ('Goose', '🪿'),
    ('Turkey', '🦃'),
    ('Farm dog', '🐕'),
    ('Farm cat', '🐈'),
    ('Bee', '🐝'),
    ('Earthworm', '🪱'),
    ('Mule', '🫏'),
    ('Yak', '🐂'),
    ('Llama', '🦙'),
    ('Alpaca', '🦙'),
    ('Camel', '🐪'),
  ],
  'wild_animals': [
    ('Lion', '🦁'),
    ('Tiger', '🐯'),
    ('Leopard', '🐆'),
    ('Cheetah', '🐆'),
    ('Elephant', '🐘'),
    ('Giraffe', '🦒'),
    ('Zebra', '🦓'),
    ('Gorilla', '🦍'),
    ('Monkey', '🐒'),
    ('Chimpanzee', '🐵'),
    ('Bear', '🐻'),
    ('Polar bear', '🐻‍❄️'),
    ('Panda', '🐼'),
    ('Wolf', '🐺'),
    ('Fox', '🦊'),
    ('Deer', '🦌'),
    ('Moose', '🫎'),
    ('Rhinoceros', '🦏'),
    ('Hippopotamus', '🦛'),
    ('Kangaroo', '🦘'),
    ('Koala', '🐨'),
    ('Sloth', '🦥'),
    ('Otter', '🦦'),
    ('Badger', '🦡'),
    ('Skunk', '🦨'),
    ('Raccoon', '🦝'),
    ('Wild boar', '🐗'),
    ('Bison', '🦬'),
    ('Antelope', '🦌'),
    ('Hyena', '🐕'),
  ],
  'sea_animals': [
    ('Fish', '🐟'),
    ('Clownfish', '🐠'),
    ('Shark', '🦈'),
    ('Whale', '🐋'),
    ('Dolphin', '🐬'),
    ('Octopus', '🐙'),
    ('Squid', '🦑'),
    ('Jellyfish', '🪼'),
    ('Starfish', '⭐'),
    ('Seahorse', '🐴'),
    ('Crab', '🦀'),
    ('Lobster', '🦞'),
    ('Shrimp', '🦐'),
    ('Oyster', '🦪'),
    ('Sea turtle', '🐢'),
    ('Seal', '🦭'),
    ('Walrus', '🦭'),
    ('Pufferfish', '🐡'),
    ('Stingray', '🐟'),
    ('Eel', '🐍'),
    ('Tuna', '🐟'),
    ('Salmon', '🐟'),
    ('Swordfish', '🐟'),
    ('Angelfish', '🐠'),
    ('Coral', '🪸'),
    ('Sea urchin', '🟣'),
    ('Sea snail', '🐌'),
    ('Penguin', '🐧'),
    ('Pelican', '🐦'),
    ('Orca', '🐋'),
  ],
  'insects': [
    ('Butterfly', '🦋'),
    ('Bee', '🐝'),
    ('Ant', '🐜'),
    ('Ladybird', '🐞'),
    ('Beetle', '🪲'),
    ('Cricket', '🦗'),
    ('Grasshopper', '🦗'),
    ('Mosquito', '🦟'),
    ('Fly', '🪰'),
    ('Cockroach', '🪳'),
    ('Caterpillar', '🐛'),
    ('Dragonfly', '🦋'),
    ('Moth', '🦋'),
    ('Firefly', '✨'),
    ('Wasp', '🐝'),
    ('Praying mantis', '🦗'),
    ('Stick insect', '🌿'),
    ('Termite', '🐜'),
    ('Flea', '🔸'),
    ('Aphid', '🟢'),
    ('Cicada', '🪲'),
    ('Centipede', '🐛'),
    ('Millipede', '🐛'),
    ('Spider', '🕷️'),
    ('Scorpion', '🦂'),
    ('Snail', '🐌'),
    ('Slug', '🐌'),
    ('Earthworm', '🪱'),
    ('Silkworm', '🐛'),
    ('Hornet', '🐝'),
  ],
  'flowers_plants': [
    ('Rose', '🌹'),
    ('Lotus', '🪷'),
    ('Sunflower', '🌻'),
    ('Tulip', '🌷'),
    ('Hibiscus', '🌺'),
    ('Daisy', '🌼'),
    ('Jasmine', '🌼'),
    ('Lily', '🪷'),
    ('Marigold', '🌼'),
    ('Orchid', '🌸'),
    ('Lavender', '🪻'),
    ('Daffodil', '🌼'),
    ('Poppy', '🌺'),
    ('Dahlia', '🌸'),
    ('Bougainvillea', '🌺'),
    ('Chrysanthemum', '🌼'),
    ('Cactus', '🌵'),
    ('Fern', '🌿'),
    ('Bamboo', '🎋'),
    ('Grass', '🌱'),
    ('Moss', '🟢'),
    ('Aloe vera', '🪴'),
    ('Money plant', '🪴'),
    ('Mint plant', '🌿'),
    ('Basil plant', '🌿'),
    ('Neem tree', '🌳'),
    ('Banyan tree', '🌳'),
    ('Palm tree', '🌴'),
    ('Pine tree', '🌲'),
    ('Mango tree', '🌳'),
  ],
  'nature': [
    ('Sun', '☀️'),
    ('Moon', '🌙'),
    ('Star', '⭐'),
    ('Sky', '🌌'),
    ('Cloud', '☁️'),
    ('Rain', '🌧️'),
    ('Rainbow', '🌈'),
    ('River', '🏞️'),
    ('Lake', '🏞️'),
    ('Pond', '🪷'),
    ('Sea', '🌊'),
    ('Ocean', '🌊'),
    ('Waterfall', '💦'),
    ('Mountain', '⛰️'),
    ('Hill', '🌄'),
    ('Valley', '🏞️'),
    ('Forest', '🌳'),
    ('Tree', '🌲'),
    ('Leaf', '🍃'),
    ('Flower', '🌸'),
    ('Grass', '🌱'),
    ('Rock', '🪨'),
    ('Sand', '🏖️'),
    ('Soil', '🟤'),
    ('Island', '🏝️'),
    ('Beach', '🏖️'),
    ('Cave', '🕳️'),
    ('Desert', '🏜️'),
    ('Volcano', '🌋'),
    ('Snow', '❄️'),
  ],
  'weather_seasons': [
    ('Sunny', '☀️'),
    ('Cloudy', '☁️'),
    ('Rainy', '🌧️'),
    ('Windy', '💨'),
    ('Stormy', '⛈️'),
    ('Snowy', '🌨️'),
    ('Foggy', '🌫️'),
    ('Hot', '🥵'),
    ('Cold', '🥶'),
    ('Warm', '🌤️'),
    ('Cool', '🍃'),
    ('Rainbow', '🌈'),
    ('Thunder', '⚡'),
    ('Lightning', '🌩️'),
    ('Raindrop', '💧'),
    ('Snowflake', '❄️'),
    ('Hail', '🧊'),
    ('Breeze', '🍃'),
    ('Spring', '🌸'),
    ('Summer', '☀️'),
    ('Rainy season', '🌧️'),
    ('Autumn', '🍂'),
    ('Winter', '⛄'),
    ('Morning', '🌅'),
    ('Afternoon', '🌞'),
    ('Evening', '🌇'),
    ('Night', '🌙'),
    ('Sunrise', '🌄'),
    ('Sunset', '🌅'),
    ('Umbrella', '☂️'),
  ],
  'clothes': [
    ('Shirt', '👕'),
    ('T-shirt', '👕'),
    ('Trousers', '👖'),
    ('Jeans', '👖'),
    ('Shorts', '🩳'),
    ('Skirt', '👗'),
    ('Dress', '👗'),
    ('Frock', '👗'),
    ('Sari', '🥻'),
    ('Kurta', '🥻'),
    ('Pyjamas', '🧥'),
    ('Sweater', '🧥'),
    ('Jacket', '🧥'),
    ('Coat', '🧥'),
    ('Raincoat', '🧥'),
    ('School uniform', '🧑‍🎓'),
    ('Night suit', '🛌'),
    ('Socks', '🧦'),
    ('Gloves', '🧤'),
    ('Scarf', '🧣'),
    ('Swimsuit', '🩱'),
    ('Tracksuit', '🏃'),
    ('Dungarees', '👖'),
    ('Blouse', '👚'),
    ('Waistcoat', '🦺'),
    ('Tights', '🧦'),
    ('Robe', '🥋'),
    ('Apron', '👩‍🍳'),
    ('Costume', '🦸'),
    ('Dhoti', '🤍'),
  ],
  'footwear_accessories': [
    ('Shoes', '👟'),
    ('Sandals', '👡'),
    ('Slippers', '🥿'),
    ('Boots', '🥾'),
    ('Rain boots', '🥾'),
    ('Sports shoes', '👟'),
    ('School shoes', '👞'),
    ('Socks', '🧦'),
    ('Hat', '👒'),
    ('Cap', '🧢'),
    ('Helmet', '⛑️'),
    ('Crown', '👑'),
    ('Glasses', '👓'),
    ('Sunglasses', '🕶️'),
    ('Watch', '⌚'),
    ('Belt', '🪢'),
    ('Tie', '👔'),
    ('Bow tie', '🎀'),
    ('Necklace', '📿'),
    ('Bracelet', '📿'),
    ('Ring', '💍'),
    ('Earrings', '💎'),
    ('Hairband', '🎀'),
    ('Hair clip', '🎀'),
    ('Backpack', '🎒'),
    ('Handbag', '👜'),
    ('Wallet', '👛'),
    ('Umbrella', '☂️'),
    ('Mask', '😷'),
    ('Badge', '📛'),
  ],
  'food': [
    ('Rice', '🍚'),
    ('Roti', '🫓'),
    ('Bread', '🍞'),
    ('Dal', '🥣'),
    ('Khichdi', '🍲'),
    ('Idli', '⚪'),
    ('Dosa', '🥞'),
    ('Upma', '🥣'),
    ('Poha', '🍚'),
    ('Pasta', '🍝'),
    ('Noodles', '🍜'),
    ('Soup', '🍲'),
    ('Salad', '🥗'),
    ('Sandwich', '🥪'),
    ('Pizza', '🍕'),
    ('Burger', '🍔'),
    ('Egg', '🥚'),
    ('Cheese', '🧀'),
    ('Yogurt', '🥣'),
    ('Paneer', '🧀'),
    ('Porridge', '🥣'),
    ('Cereal', '🥣'),
    ('Pancake', '🥞'),
    ('Biscuit', '🍪'),
    ('Cake', '🍰'),
    ('Ladoo', '🟡'),
    ('Kheer', '🥣'),
    ('Ice cream', '🍨'),
    ('Popcorn', '🍿'),
    ('Peanut', '🥜'),
  ],
  'drinks': [
    ('Water', '💧'),
    ('Milk', '🥛'),
    ('Warm milk', '🥛'),
    ('Chocolate milk', '🥛'),
    ('Coconut water', '🥥'),
    ('Lemonade', '🍋'),
    ('Orange juice', '🍊'),
    ('Apple juice', '🍎'),
    ('Mango juice', '🥭'),
    ('Grape juice', '🍇'),
    ('Pineapple juice', '🍍'),
    ('Watermelon juice', '🍉'),
    ('Carrot juice', '🥕'),
    ('Tomato juice', '🍅'),
    ('Mixed fruit juice', '🧃'),
    ('Lassi', '🥛'),
    ('Buttermilk', '🥛'),
    ('Milkshake', '🥤'),
    ('Banana shake', '🍌'),
    ('Mango shake', '🥭'),
    ('Strawberry shake', '🍓'),
    ('Smoothie', '🥤'),
    ('Soup drink', '🥣'),
    ('Herbal tea', '🍵'),
    ('Tea', '🍵'),
    ('Hot chocolate', '☕'),
    ('Sugarcane juice', '🌾'),
    ('Rose milk', '🌹'),
    ('Almond milk', '🥜'),
    ('Soy milk', '🫘'),
  ],
  'kitchen': [
    ('Plate', '🍽️'),
    ('Bowl', '🥣'),
    ('Cup', '☕'),
    ('Glass', '🥛'),
    ('Spoon', '🥄'),
    ('Fork', '🍴'),
    ('Knife', '🔪'),
    ('Pan', '🍳'),
    ('Pot', '🍲'),
    ('Lid', '⭕'),
    ('Kettle', '🫖'),
    ('Teapot', '🫖'),
    ('Bottle', '🍼'),
    ('Jar', '🫙'),
    ('Lunch box', '🍱'),
    ('Tray', '🍽️'),
    ('Rolling pin', '🪵'),
    ('Chopping board', '🟫'),
    ('Strainer', '🥣'),
    ('Grater', '🧀'),
    ('Whisk', '🥄'),
    ('Spatula', '🥄'),
    ('Tongs', '🥢'),
    ('Mixer', '🌀'),
    ('Fridge', '🧊'),
    ('Oven', '♨️'),
    ('Stove', '🔥'),
    ('Sink', '🚰'),
    ('Apron', '👩‍🍳'),
    ('Oven gloves', '🧤'),
  ],
  'home_rooms': [
    ('Home', '🏠'),
    ('Living room', '🛋️'),
    ('Bedroom', '🛏️'),
    ('Kitchen', '🍳'),
    ('Bathroom', '🛁'),
    ('Dining room', '🍽️'),
    ('Balcony', '🏡'),
    ('Garden', '🌷'),
    ('Door', '🚪'),
    ('Window', '🪟'),
    ('Wall', '🧱'),
    ('Floor', '🟫'),
    ('Roof', '🏠'),
    ('Stairs', '🪜'),
    ('Chair', '🪑'),
    ('Table', '🪵'),
    ('Sofa', '🛋️'),
    ('Bed', '🛏️'),
    ('Cupboard', '🚪'),
    ('Shelf', '📚'),
    ('Curtain', '🪟'),
    ('Carpet', '🟫'),
    ('Pillow', '🛏️'),
    ('Blanket', '🛌'),
    ('Lamp', '💡'),
    ('Fan', '🪭'),
    ('Clock', '🕐'),
    ('Mirror', '🪞'),
    ('Plant pot', '🪴'),
    ('Doorbell', '🔔'),
  ],
  'school': [
    ('School', '🏫'),
    ('Classroom', '🧑‍🏫'),
    ('Teacher', '👩‍🏫'),
    ('Student', '🧑‍🎓'),
    ('Book', '📖'),
    ('Notebook', '📓'),
    ('Pencil', '✏️'),
    ('Eraser', '🩹'),
    ('Sharpener', '🔺'),
    ('Crayon', '🖍️'),
    ('Ruler', '📏'),
    ('School bag', '🎒'),
    ('Lunch box', '🍱'),
    ('Water bottle', '🍼'),
    ('Desk', '🪑'),
    ('Chair', '🪑'),
    ('Blackboard', '⬛'),
    ('Chalk', '🤍'),
    ('Marker', '🖊️'),
    ('Paper', '📄'),
    ('Scissors', '✂️'),
    ('Glue', '🧴'),
    ('Paint', '🎨'),
    ('Paintbrush', '🖌️'),
    ('Computer', '💻'),
    ('Library', '📚'),
    ('Playground', '🛝'),
    ('School bus', '🚌'),
    ('Bell', '🔔'),
    ('Uniform', '🧑‍🎓'),
  ],
  'toys': [
    ('Teddy bear', '🧸'),
    ('Ball', '⚽'),
    ('Doll', '🪆'),
    ('Toy car', '🚗'),
    ('Toy train', '🚂'),
    ('Blocks', '🧱'),
    ('Puzzle', '🧩'),
    ('Kite', '🪁'),
    ('Yo-yo', '🪀'),
    ('Spinning top', '🌀'),
    ('Balloon', '🎈'),
    ('Drum', '🥁'),
    ('Robot', '🤖'),
    ('Rocking horse', '🐴'),
    ('Jump rope', '➰'),
    ('Marbles', '🔵'),
    ('Building set', '🏗️'),
    ('Finger puppet', '🖐️'),
    ('Toy kitchen', '🍳'),
    ('Tea set', '🫖'),
    ('Board game', '🎲'),
    ('Playing cards', '🃏'),
    ('Frisbee', '🥏'),
    ('Water gun', '💦'),
    ('Bubble wand', '🫧'),
    ('Play dough', '🌈'),
    ('Coloring book', '📕'),
    ('Sticker book', '⭐'),
    ('Scooter', '🛴'),
    ('Tricycle', '🚲'),
  ],
  'sports': [
    ('Football', '⚽'),
    ('Cricket', '🏏'),
    ('Basketball', '🏀'),
    ('Tennis', '🎾'),
    ('Badminton', '🏸'),
    ('Hockey', '🏑'),
    ('Table tennis', '🏓'),
    ('Volleyball', '🏐'),
    ('Baseball', '⚾'),
    ('Rugby', '🏉'),
    ('Golf', '⛳'),
    ('Swimming', '🏊'),
    ('Running', '🏃'),
    ('Cycling', '🚴'),
    ('Skating', '⛸️'),
    ('Skiing', '⛷️'),
    ('Gymnastics', '🤸'),
    ('Boxing', '🥊'),
    ('Wrestling', '🤼'),
    ('Archery', '🏹'),
    ('Horse riding', '🏇'),
    ('Surfing', '🏄'),
    ('Rowing', '🚣'),
    ('Climbing', '🧗'),
    ('Bowling', '🎳'),
    ('Carrom', '🔴'),
    ('Chess', '♟️'),
    ('Kabaddi', '🤼'),
    ('Jump rope', '➰'),
    ('Yoga', '🧘'),
  ],
  'instruments': [
    ('Drum', '🥁'),
    ('Guitar', '🎸'),
    ('Piano', '🎹'),
    ('Violin', '🎻'),
    ('Trumpet', '🎺'),
    ('Saxophone', '🎷'),
    ('Flute', '🪈'),
    ('Harmonica', '🎵'),
    ('Xylophone', '🎼'),
    ('Tambourine', '🪘'),
    ('Tabla', '🪘'),
    ('Dhol', '🥁'),
    ('Sitar', '🪕'),
    ('Veena', '🪕'),
    ('Harp', '🎵'),
    ('Cello', '🎻'),
    ('Clarinet', '🎵'),
    ('Trombone', '🎺'),
    ('French horn', '📯'),
    ('Tuba', '🎺'),
    ('Accordion', '🪗'),
    ('Keyboard', '🎹'),
    ('Cymbals', '🎶'),
    ('Triangle', '🔺'),
    ('Maracas', '🪇'),
    ('Bells', '🔔'),
    ('Banjo', '🪕'),
    ('Mandolin', '🪕'),
    ('Recorder', '🪈'),
    ('Microphone', '🎤'),
  ],
  'helpers': [
    ('Doctor', '🧑‍⚕️'),
    ('Nurse', '👩‍⚕️'),
    ('Teacher', '👩‍🏫'),
    ('Police officer', '👮'),
    ('Firefighter', '🧑‍🚒'),
    ('Farmer', '🧑‍🌾'),
    ('Chef', '🧑‍🍳'),
    ('Baker', '🥖'),
    ('Driver', '🧑‍✈️'),
    ('Bus driver', '🚌'),
    ('Pilot', '🧑‍✈️'),
    ('Train driver', '🚂'),
    ('Postman', '📮'),
    ('Soldier', '🪖'),
    ('Dentist', '🦷'),
    ('Veterinarian', '🐶'),
    ('Scientist', '🧑‍🔬'),
    ('Engineer', '🧑‍🔧'),
    ('Mechanic', '🧑‍🔧'),
    ('Carpenter', '🪚'),
    ('Plumber', '🔧'),
    ('Electrician', '💡'),
    ('Gardener', '🧑‍🌾'),
    ('Cleaner', '🧹'),
    ('Tailor', '🧵'),
    ('Barber', '💈'),
    ('Shopkeeper', '🏪'),
    ('Librarian', '📚'),
    ('Lifeguard', '🛟'),
    ('Sanitation worker', '🧹'),
  ],
  'places': [
    ('Home', '🏠'),
    ('School', '🏫'),
    ('Park', '🏞️'),
    ('Playground', '🛝'),
    ('Hospital', '🏥'),
    ('Clinic', '🩺'),
    ('Police station', '🚓'),
    ('Fire station', '🚒'),
    ('Post office', '🏣'),
    ('Library', '📚'),
    ('Market', '🛍️'),
    ('Grocery shop', '🏪'),
    ('Bakery', '🥖'),
    ('Restaurant', '🍽️'),
    ('Bank', '🏦'),
    ('Bus stop', '🚏'),
    ('Railway station', '🚉'),
    ('Airport', '🛫'),
    ('Zoo', '🦁'),
    ('Museum', '🏛️'),
    ('Farm', '🚜'),
    ('Garden', '🌷'),
    ('Beach', '🏖️'),
    ('Temple', '🛕'),
    ('Church', '⛪'),
    ('Mosque', '🕌'),
    ('Gurudwara', '🛕'),
    ('Cinema', '🎬'),
    ('Swimming pool', '🏊'),
    ('Petrol station', '⛽'),
  ],
  'actions': [
    ('Walk', '🚶'),
    ('Run', '🏃'),
    ('Jump', '🦘'),
    ('Hop', '🐰'),
    ('Skip', '➰'),
    ('Sit', '🪑'),
    ('Stand', '🧍'),
    ('Sleep', '😴'),
    ('Wake up', '🥱'),
    ('Eat', '🍽️'),
    ('Drink', '🥤'),
    ('Read', '📖'),
    ('Write', '✍️'),
    ('Draw', '🎨'),
    ('Color', '🖍️'),
    ('Sing', '🎤'),
    ('Dance', '💃'),
    ('Clap', '👏'),
    ('Wave', '👋'),
    ('Smile', '😊'),
    ('Laugh', '😂'),
    ('Cry', '😢'),
    ('Talk', '🗣️'),
    ('Listen', '👂'),
    ('Look', '👀'),
    ('Open', '📖'),
    ('Close', '📕'),
    ('Wash', '🧼'),
    ('Brush', '🪥'),
    ('Play', '🛝'),
  ],
};
